import { cmd } from '../command.js';
import PDFDocument from 'pdfkit';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);

cmd({
    pattern: "topdf",
    alias: ["pdf", "maketextpdf"],
    desc: "Convert text or a quoted message into a PDF document.",
    category: "utility",
    react: "📄",
    filename: __filename
},
async (conn, mek, m, { from, q, quoted, reply }) => {
    try {
        // 1. Text Extraction Logic
        // Prioritizes quoted text, then manual input 'q'
        let textToConvert = q;
        if (quoted && quoted.msg && typeof quoted.msg === 'string') {
            textToConvert = quoted.msg;
        } else if (quoted && quoted.text) {
            textToConvert = quoted.text;
        }

        if (!textToConvert) {
            return reply("✍️ *𝐏𝐥𝐞𝐚𝐬𝐞 𝐩𝐫𝐨𝐯𝐢𝐝𝐞 𝐭𝐞𝐱𝐭!*\n\nExample: .topdf Zimbabwe is beautiful 🇿🇼\nOr: Reply to a long text with .topdf");
        }

        // 2. PDF Generation Logic
        const doc = new PDFDocument();
        let buffers = [];
        
        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', async () => {
            const pdfBuffer = Buffer.concat(buffers);

            // 3. Stylized Output (Zero Footprint)
            const caption = `📄 *𝐏𝐃𝐅 𝐆𝐄𝐍𝐄𝐑𝐀𝐓𝐄𝐃 𝐒𝐔𝐂𝐂𝐄𝐒𝐒𝐅𝐔𝐋𝐋𝐘*\n\n` +
                `✨ *Filename:* watsonxd.pdf\n\n` +
                `> © 𝐏𝐎𝐖𝐄𝐑𝐄𝐃 𝐁𝐘 𝐏𝐑𝐄𝐂𝐈𝐎𝐔𝐒-𝐌𝐃`;

            await conn.sendMessage(from, {
                document: pdfBuffer,
                mimetype: 'application/pdf',
                fileName: 'watsonxd.pdf',
                caption: caption,
                contextInfo: {
                    forwardingScore: 999,
                    isForwarded: true
                }
            }, { quoted: mek });
        });

        // Add branding header inside the PDF
        doc.fontSize(20).text('𝐏𝐑𝐄𝐂𝐈𝐎𝐔𝐒-𝐌𝐃 𝐃𝐎𝐂𝐔𝐌𝐄𝐍𝐓', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(textToConvert, {
            align: 'left',
            lineGap: 5
        });
        doc.moveDown();
        doc.fontSize(10).fillColor('grey').text('Generated by Watson Xd', { align: 'right' });

        // Finalize
        doc.end();

    } catch (e) {
        console.error("PDF Conversion Error:", e);
        reply("⚠️ *𝐒𝐘𝐒𝐓𝐄𝐌 𝐄𝐑𝐑𝐎𝐑:* Failed to generate PDF.");
    }
});
